### ISSUE TITLE
Cusp values are coming wrong for sidereal 

### ISSUE THREAD

**Issue by vaishalithaker** [vsmithers1087/SwissEphemeris#16]
cusp values are coming wrong for sidereal astrology. please help

**Comment by vsmithers1087** [comment]
Hi @vaishalithaker,

You are correct. At the moment, there is no support for sidereal house cusps. This is something that needs to be added to the project.

**Comment by vsmithers1087** [comment]
`.sidereal` property has been added to `Cusp` https://github.com/vsmithers1087/SwissEphemeris/releases/tag/0.0.14
